db:
  image: dylanlindgren/docker-mariadb
  volumes:
    - /Users/dunghv/Code/myapp/mariadb:/data/mariadb
  ports:
    - "3306:3306"
  privileged: true

data:
  image: docker-laravel-data
  volumes:
    - /Users/dunghv/Code/myapp:/data
  privileged: true

php:
  image: docker-laravel-php7fpm
  volumes_from:
    - data
  links:
    - db:db
  privileged: true

web:
  image: docker-laravel-nginx
  volumes_from:
    - data
  links:
    - php:fpm
  ports:
    - "80:80"
  privileged: true

composer:
  image: docker-laravel-composer
  volumes_from:
    - data

artisan:
  image: docker-laravel-artisan
  volumes_from:
    - data
  links:
    - db:db

bower:
  image: docker-laravel-bower
  volumes_from:
    - data