version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    privileged: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  data:
    image: dunghv/laravel-data
    volumes:
      - ~/Code/myapp:/data:rw
    privileged: true

  phpfpm:
    image: dunghv/laravel-phpfpm
    volumes_from:
      - data
    links:
      - db
    privileged: true
    environment:
      XDEBUG_REMOTE_HOST: 192.168.3.104
      XDEBUG_IDEKEY: PHPSTORM

  web:
    image: dunghv/laravel-nginx
    volumes_from:
      - data
    links:
      - phpfpm
    ports:
      - "80:80"
    privileged: true
    depends_on:
      - db
      - phpfpm

  composer:
    image: dunghv/laravel-composer
    volumes_from:
      - data

  phpcli:
    image: dunghv/laravel-phpcli

  artisan:
    image: dunghv/laravel-artisan
    volumes_from:
      - data
    links:
      - db
    depends_on:
      - phpcli

  bower:
    image: dunghv/laravel-bower
    volumes_from:
      - data

  phpunit:
    image: dunghv/laravel-phpunit
    volumes_from:
      - data
    depends_on:
      - phpcli